### ISSUE TITLE
Add functions plz

### ISSUE THREAD

**Issue by MineFlayerPC** [Robitobi01/SARC#1]
Add the ability to walk, fall, please

**Comment by Nessiesson** [comment]
What do you mean? Being able to walk, fall, etc. is beyond the scope of this project. I recommend you look at https://github.com/ORelio/Minecraft-Console-Client or https://github.com/ammaraskar/pyCraft (etc.) for libraries designed for such utility.

**Comment by Robitobi01** [comment]
How should that be implemented? The ability to walk is already existing in the protocol, you only need to send the correct packets.
If you understand how SARC works you should be able to add such functions yourself, this project was intended to be a rather simple terminal client. How do you plan on processing the inputs?
